# Use zsh as default
set -g default-shell /bin/zsh

# Terminal
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB,hyperlinks"

# General
set -g set-clipboard on         # Use system clipboard
set -g detach-on-destroy off    # Don't exit from tmux when closing a session
set -g escape-time 0            # Remove ESC delay for Neovim
set -g history-limit 1000000    # Increase scrollback history
set -g mouse on                 # Enable mouse support
set -g status-interval 3        # Refresh status bar every 3 seconds
set -g allow-passthrough on     # Allow applications to bypass tmux (e.g. image preview)
set -g status-position top

# Prefix key
unbind C-b
set -g prefix C-Space

# Reload configuration
unbind r
bind r source-file "$HOME/.config/tmux/tmux.conf" \; display-message "tmux config reloaded"

# Split panes in current working directory
unbind %
bind \\ split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

# New window in current working directory
bind c new-window -c "#{pane_current_path}"

# Resize panes with Vim keys
bind -r h resize-pane -L 5
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5

# Toggle pane zoom
bind -r m resize-pane -Z

# Copy mode
set-window-option -g mode-keys vi

bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Paste buffer
bind P paste-buffer

# Keep copy mode active when dragging with the mouse
unbind -T copy-mode-vi MouseDragEnd1Pane

# Window numbering
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

# TPM plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor'

# Theme
if-shell '[ "$TMUX_THEME" = "nord" ]' \
    'source-file "$HOME/.config/tmux/themes/nord.conf"' \
    'source-file "$HOME/.config/tmux/themes/onedark.conf"'

# Resurrect
set -g @resurrect-capture-pane-contents on
# set -g @continuum-restore on

# Initialize TPM (keep this as the last line)
run "$HOME/.tmux/plugins/tpm/tpm"